#!/usr/bin/env python3
# This file is placed in the Public Domain.


"documentation"


import os


def popen(txt):
    for line in os.popen(txt).readlines():
        print(line.rstrip())


if os.path.exists("env"):
     print("environment is there")
else:
     print("creating environment")
     popen("fin/env")

popen("env/bin/pip3 install -r docs/requirements.txt --upgrade --force-reinstall --no-cache-dir --no-deps")
popen("env/bin/python3 env/bin/sphinx-build docs html")
